"""
C Unit Test Runner — Ceedling + Unity
A desktop GUI to browse your C project, pick functions, add test cases, and run tests.
Requirements: Python 3.8+, Ruby, Ceedling gem, GCC (via MinGW or MSYS2 on Windows)
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
import os, re, json, subprocess, threading, shutil, sys
from pathlib import Path

# ─── Theme ───────────────────────────────────────────────────────────────────
BG        = "#1e1e2e"
BG2       = "#2a2a3e"
BG3       = "#313145"
ACCENT    = "#7c6af7"
ACCENT2   = "#a78bfa"
GREEN     = "#4ade80"
RED       = "#f87171"
YELLOW    = "#facc15"
TEXT      = "#e2e8f0"
TEXT2     = "#94a3b8"
BORDER    = "#3f3f5c"
MONO      = ("Consolas", 11)
SANS      = ("Segoe UI", 10)
SANS_B    = ("Segoe UI", 10, "bold")
SANS_LG   = ("Segoe UI", 13, "bold")

# ─── C function parser ────────────────────────────────────────────────────────
FUNC_RE = re.compile(
    r'^\s*'
    r'(?:(?:static|inline|extern|const)\s+)*'
    r'(?P<ret>(?:unsigned\s+)?(?:int|long|short|char|float|double|void|bool|uint8_t|uint16_t|uint32_t|int8_t|int16_t|int32_t|size_t|[A-Z_][A-Z0-9_]*)\s*\*?)\s+'
    r'(?P<name>[a-zA-Z_][a-zA-Z0-9_]*)\s*'
    r'\((?P<params>[^)]*)\)\s*\{',
    re.MULTILINE
)

def parse_functions(path):
    try:
        src = Path(path).read_text(encoding="utf-8", errors="ignore")
        # strip block comments
        src = re.sub(r'/\*.*?\*/', '', src, flags=re.DOTALL)
        src = re.sub(r'//[^\n]*', '', src)
        fns = []
        for m in FUNC_RE.finditer(src):
            name = m.group("name")
            if name in ("if","for","while","switch","return","else"): continue
            fns.append({
                "name":   name,
                "ret":    m.group("ret").strip(),
                "params": [p.strip() for p in m.group("params").split(",") if p.strip() and p.strip() != "void"],
                "file":   str(path),
            })
        return fns
    except Exception as e:
        return []

def scan_project(folder):
    fns = []
    for root, dirs, files in os.walk(folder):
        dirs[:] = [d for d in dirs if d not in ("build","_build","test","tests",".git","vendor")]
        for f in files:
            if f.endswith(".c") or f.endswith(".h"):
                fns.extend(parse_functions(os.path.join(root, f)))
    seen = set()
    unique = []
    for fn in fns:
        if fn["name"] not in seen:
            seen.add(fn["name"])
            unique.append(fn)
    return unique

# ─── Test data store ─────────────────────────────────────────────────────────
class TestStore:
    def __init__(self):
        self.project_folder = ""
        self.functions = []        # [{name, ret, params, file}]
        self.tests = {}            # {fn_name: [{inputs:[...], expected, label, mock}]}
        self._save_path = ""

    def set_project(self, folder):
        self.project_folder = folder
        self.functions = scan_project(folder)
        self._save_path = os.path.join(folder, ".ctest_runner.json")
        self._load()

    def _load(self):
        if os.path.exists(self._save_path):
            try:
                data = json.loads(Path(self._save_path).read_text())
                self.tests = data.get("tests", {})
            except: pass

    def save(self):
        if self._save_path:
            Path(self._save_path).write_text(json.dumps({"tests": self.tests}, indent=2))

    def add_test(self, fn_name, inputs, expected, label="", mock_setup=""):
        if fn_name not in self.tests:
            self.tests[fn_name] = []
        self.tests[fn_name].append({
            "inputs": inputs, "expected": expected,
            "label": label or f"test_{len(self.tests[fn_name])+1}",
            "mock": mock_setup
        })
        self.save()

    def remove_test(self, fn_name, idx):
        if fn_name in self.tests and 0 <= idx < len(self.tests[fn_name]):
            self.tests[fn_name].pop(idx)
            self.save()

    def get_tests(self, fn_name):
        return self.tests.get(fn_name, [])

# ─── Unity / Ceedling code generator ─────────────────────────────────────────
def sanitize_label(s):
    return re.sub(r'[^a-zA-Z0-9_]', '_', s)

def generate_test_c(fn_info, test_cases, include_header=None):
    """Delegates to generate_test_c_with_include; kept for backward compat."""
    header = Path(fn_info["file"]).with_suffix(".h")
    if include_header:
        inc_line = f'#include "{include_header}"'
    else:
        inc_line = build_include_line(fn_info, header)
    return generate_test_c_with_include(fn_info, test_cases, inc_line)


def generate_test_c_with_include(fn_info, test_cases, include_line):
    fn  = fn_info["name"]
    ret = fn_info["ret"]
    lines = [
        "/* Auto-generated by C Test Runner */",
        '#include "unity.h"',
        include_line,
        "",
        "void setUp(void) {}",
        "void tearDown(void) {}",
        "",
    ]
    for i, tc in enumerate(test_cases):
        label    = sanitize_label(tc.get("label", f"test_{i+1}"))
        inputs   = tc.get("inputs", [])
        expected = tc.get("expected", "0")
        mock     = tc.get("mock", "").strip()
        args     = ", ".join(str(x) for x in inputs)
        lines.append(f"void test_{fn}_{label}(void) {{")
        if mock:
            for ml in mock.splitlines():
                lines.append(f"    {ml.strip()}")
        if ret.strip() == "void":
            lines.append(f"    {fn}({args});")
            lines.append(f"    TEST_PASS();")
        elif ret.strip() in ("float", "double"):
            lines.append(f"    TEST_ASSERT_EQUAL_FLOAT({expected}, {fn}({args}));")
        elif ret.strip() in ("char*", "char *", "const char*", "const char *"):
            lines.append(f'    TEST_ASSERT_EQUAL_STRING("{expected}", {fn}({args}));')
        else:
            lines.append(f"    TEST_ASSERT_EQUAL({expected}, {fn}({args}));")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)

def setup_ceedling_project(project_folder, test_name, test_c_content, source_file):
    build_dir = Path(project_folder) / "_ctest_build"
    build_dir.mkdir(exist_ok=True)
    src_dir  = build_dir / "src"
    test_dir = build_dir / "test"
    src_dir.mkdir(exist_ok=True)
    test_dir.mkdir(exist_ok=True)

    # Copy source file
    src_name = Path(source_file).name
    shutil.copy2(source_file, src_dir / src_name)
    # Copy header if exists
    header = Path(source_file).with_suffix(".h")
    if header.exists():
        shutil.copy2(header, src_dir / header.name)

    # Write test file
    test_file = test_dir / f"test_{test_name}.c"
    test_file.write_text(test_c_content)

    # Write project.yml for Ceedling
    header_name = header.name if header.exists() else src_name
    proj_yml = f""":project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_

:paths:
  :test:
    - test/**
  :source:
    - src/**
  :include:
    - src/**

:defines:
  :test: []

:tools:
  :test_compiler:
    :executable: gcc
    :arguments:
      - -std=c99
      - -Wall
      - ${{1}}
      - -o ${{2}}
  :test_linker:
    :executable: gcc
    :arguments:
      - ${{1}}
      - -o ${{2}}

:unity:
  :use_param_helper_macros: TRUE

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
"""
    (build_dir / "project.yml").write_text(proj_yml)
    return build_dir, test_file, header_name

def strip_main(source_text):
    """
    Remove the main() function body from C source so it doesn't conflict
    with the Unity test runner's own main(). Handles both:
      int main(void) { ... }
      int main(int argc, char* argv[]) { ... }
    Uses brace counting to find the full body regardless of length.
    """
    # Find start of main() definition (not a call)
    pattern = re.compile(
        r'\bint\s+main\s*\([^)]*\)\s*\{',
        re.MULTILINE
    )
    m = pattern.search(source_text)
    if not m:
        return source_text  # no main found, nothing to strip

    start = m.start()
    brace_pos = source_text.index('{', m.start())
    depth = 0
    i = brace_pos
    while i < len(source_text):
        if source_text[i] == '{':
            depth += 1
        elif source_text[i] == '}':
            depth -= 1
            if depth == 0:
                end = i + 1
                break
        i += 1
    else:
        end = len(source_text)

    # Replace with a comment so line numbers don't shift dramatically
    removed = source_text[start:end]
    lines = removed.count('\n')
    placeholder = "/* main() removed by C Test Runner */\n" * max(1, lines)
    return source_text[:start] + placeholder + source_text[end:]


def make_source_without_main(source_file, build_dir):
    """
    Read source, strip main(), write to build dir as <name>_testable.c
    Returns path to the stripped file.
    """
    original = Path(source_file).read_text(encoding="utf-8", errors="ignore")
    stripped = strip_main(original)
    out_name = Path(source_file).stem + "_testable.c"
    out_path = build_dir / out_name
    out_path.write_text(stripped, encoding="utf-8")
    return out_path


def build_include_line(fn_info, header):
    """
    Return the #include line(s) to put in the test file.
    If a .h exists, use it. Otherwise forward-declare the function directly.
    """
    if header and header.exists():
        return f'#include "{header.name}"'
    # No header — emit a forward declaration so the test file compiles
    fn   = fn_info["name"]
    ret  = fn_info["ret"]
    params = ", ".join(fn_info["params"]) if fn_info["params"] else "void"
    return f"/* no header found — forward declaration */\n{ret} {fn}({params});"


def run_with_unity_directly(project_folder, fn_info, test_cases):
    """Compile + run with Unity directly (no Ceedling needed)."""
    build_dir = Path(project_folder) / "_ctest_build"
    build_dir.mkdir(exist_ok=True)

    source_file = Path(fn_info["file"])
    print
    header      = source_file.with_suffix(".h")

    # ── Download Unity if not present ────────────────────────────────────────
    unity_dir = build_dir / "unity"
    unity_c   = unity_dir / "unity.c"
    unity_h   = unity_dir / "unity.h"
    unity_ih  = unity_dir / "unity_internals.h"

    if not unity_c.exists():
        yield "INFO", "Downloading Unity framework...\n"
        unity_dir.mkdir(exist_ok=True)
        try:
            import urllib.request
            base = "https://raw.githubusercontent.com/ThrowTheSwitch/Unity/master/src/"
            for fname, dest in [("unity.c", unity_c), ("unity.h", unity_h),
                                 ("unity_internals.h", unity_ih)]:
                urllib.request.urlretrieve(base + fname, dest)
            yield "INFO", "Unity downloaded.\n"
        except Exception as e:
            yield "ERROR", (
                f"Could not download Unity: {e}\n"
                f"Manually place unity.c / unity.h / unity_internals.h in:\n  {unity_dir}\n"
            )
            return

    # ── Strip main() from source so there's no duplicate ─────────────────────
    yield "INFO", f"Preprocessing {source_file.name} (removing main if present)...\n"
    testable_src = make_source_without_main(source_file, build_dir)

    # ── Generate test file ────────────────────────────────────────────────────
    include_line = build_include_line(fn_info, header)
    test_name    = fn_info["name"]
    test_c       = generate_test_c_with_include(fn_info, test_cases, include_line)
    test_file    = build_dir / f"test_{test_name}.c"
    test_file.write_text(test_c, encoding="utf-8")

    # ── Generate runner (main) ────────────────────────────────────────────────
    runner_c  = build_dir / f"runner_{test_name}.c"
    test_fns  = [
        f"test_{test_name}_{sanitize_label(tc.get('label', f'test_{i+1}'))}"
        for i, tc in enumerate(test_cases)
    ]
    runner_body  = '#include "unity.h"\n'
    runner_body += "".join(f"extern void {f}(void);\n" for f in test_fns)
    runner_body += "\nint main(void) {\n    UNITY_BEGIN();\n"
    runner_body += "".join(f"    RUN_TEST({f});\n" for f in test_fns)
    runner_body += "    return UNITY_END();\n}\n"
    runner_c.write_text(runner_body, encoding="utf-8")

    # ── Build include paths ───────────────────────────────────────────────────
    includes = [f"-I{unity_dir}", f"-I{source_file.parent}"]
    if header.exists() and str(header.parent) not in [str(source_file.parent)]:
        includes.append(f"-I{header.parent}")

    exe = build_dir / f"test_{test_name}.exe"
    cmd = [
        "gcc", "-std=c99", "-Wall",
        str(test_file),
        str(runner_c),
        str(unity_c),
        str(testable_src),   # ← stripped copy, no main()
        *includes,
        "-o", str(exe),
    ]

    yield "CMD", "Compiling:\n  " + "\n  ".join(cmd) + "\n\n"
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, cwd=str(build_dir))
        if r.stdout: yield "OUT", r.stdout
        if r.stderr: yield "ERR", r.stderr + "\n"
        if r.returncode != 0:
            yield "ERROR", f"Compilation failed (exit {r.returncode})\n"
            return
        yield "INFO", "Compilation successful. Running tests...\n\n"
        r2 = subprocess.run([str(exe)], capture_output=True, text=True, cwd=str(build_dir))
        if r2.stdout: yield "RESULT", r2.stdout
        if r2.stderr: yield "ERR", r2.stderr
    except FileNotFoundError:
        yield "ERROR", (
            "gcc not found in PATH.\n"
            "Install MinGW-w64 from https://winlibs.com and add its bin/ folder to PATH.\n"
        )

# ─── Main App ─────────────────────────────────────────────────────────────────
class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("C Unit Test Runner — Unity + Ceedling")
        self.geometry("1200x780")
        self.minsize(900, 600)
        self.configure(bg=BG)
        self.store = TestStore()
        self.selected_fn = None
        self._build_ui()

    # ── UI construction ──────────────────────────────────────────────────────
    def _build_ui(self):
        # Top bar
        top = tk.Frame(self, bg=BG2, pady=8, padx=14)
        top.pack(fill="x")
        tk.Label(top, text="⬡ C Test Runner", font=("Segoe UI", 14, "bold"),
                 bg=BG2, fg=ACCENT2).pack(side="left")
        btn_open = tk.Button(top, text="📂  Open Project Folder", font=SANS_B,
                             bg=ACCENT, fg="white", relief="flat", padx=14, pady=5,
                             cursor="hand2", command=self.open_folder)
        btn_open.pack(side="right", padx=4)
        self.folder_lbl = tk.Label(top, text="No project loaded", font=SANS,
                                   bg=BG2, fg=TEXT2)
        self.folder_lbl.pack(side="right", padx=12)

        # Main pane
        pane = tk.PanedWindow(self, orient="horizontal", bg=BG, sashwidth=4,
                              sashrelief="flat")
        pane.pack(fill="both", expand=True, padx=10, pady=(6,10))

        # Left: function list
        left = tk.Frame(pane, bg=BG2, bd=0)
        pane.add(left, minsize=220, width=260)
        tk.Label(left, text="Functions", font=SANS_B, bg=BG2, fg=TEXT2,
                 pady=8).pack(fill="x", padx=10)
        self.fn_search = tk.Entry(left, font=SANS, bg=BG3, fg=TEXT,
                                  insertbackground=TEXT, relief="flat",
                                  highlightthickness=1, highlightcolor=ACCENT)
        self.fn_search.pack(fill="x", padx=10, pady=(0,6))
        self.fn_search.bind("<KeyRelease>", lambda e: self._filter_fns())
        self.fn_search.insert(0, "Search functions...")
        self.fn_search.config(fg=TEXT2)
        self.fn_search.bind("<FocusIn>",  lambda e: self._clear_search())
        self.fn_search.bind("<FocusOut>", lambda e: self._restore_search())

        frame_list = tk.Frame(left, bg=BG2)
        frame_list.pack(fill="both", expand=True, padx=10, pady=(0,10))
        sb = tk.Scrollbar(frame_list)
        sb.pack(side="right", fill="y")
        self.fn_listbox = tk.Listbox(frame_list, yscrollcommand=sb.set,
                                     font=MONO, bg=BG3, fg=TEXT,
                                     selectbackground=ACCENT, selectforeground="white",
                                     relief="flat", bd=0, activestyle="none",
                                     highlightthickness=0)
        self.fn_listbox.pack(fill="both", expand=True)
        sb.config(command=self.fn_listbox.yview)
        self.fn_listbox.bind("<<ListboxSelect>>", self.on_fn_select)

        # Right: test panel
        right = tk.Frame(pane, bg=BG)
        pane.add(right, minsize=400)

        # Function info bar
        self.fn_info_frame = tk.Frame(right, bg=BG2, pady=6, padx=12)
        self.fn_info_frame.pack(fill="x", pady=(0,6))
        self.fn_sig_lbl = tk.Label(self.fn_info_frame, text="← Select a function",
                                   font=MONO, bg=BG2, fg=ACCENT2, anchor="w")
        self.fn_sig_lbl.pack(side="left")
        self.fn_file_lbl = tk.Label(self.fn_info_frame, text="", font=("Segoe UI",9),
                                    bg=BG2, fg=TEXT2)
        self.fn_file_lbl.pack(side="right")

        # Add test case form
        form = tk.LabelFrame(right, text=" Add Test Case ", font=SANS_B,
                             bg=BG2, fg=TEXT2, bd=1, relief="flat",
                             highlightbackground=BORDER, highlightthickness=1)
        form.pack(fill="x", padx=0, pady=(0,6))

        row1 = tk.Frame(form, bg=BG2)
        row1.pack(fill="x", padx=10, pady=(8,4))
        tk.Label(row1, text="Label:", font=SANS, bg=BG2, fg=TEXT2, width=9,
                 anchor="w").pack(side="left")
        self.e_label = tk.Entry(row1, font=MONO, bg=BG3, fg=TEXT,
                                insertbackground=TEXT, relief="flat",
                                highlightthickness=1, highlightcolor=ACCENT)
        self.e_label.pack(side="left", fill="x", expand=True)

        row2 = tk.Frame(form, bg=BG2)
        row2.pack(fill="x", padx=10, pady=4)
        tk.Label(row2, text="Inputs:", font=SANS, bg=BG2, fg=TEXT2, width=9,
                 anchor="w").pack(side="left")
        self.e_inputs = tk.Entry(row2, font=MONO, bg=BG3, fg=TEXT,
                                 insertbackground=TEXT, relief="flat",
                                 highlightthickness=1, highlightcolor=ACCENT)
        self.e_inputs.pack(side="left", fill="x", expand=True)
        self.inputs_hint = tk.Label(row2, text="comma-separated, e.g. 3, 5",
                                    font=("Segoe UI",9), bg=BG2, fg=TEXT2)
        self.inputs_hint.pack(side="left", padx=8)

        row3 = tk.Frame(form, bg=BG2)
        row3.pack(fill="x", padx=10, pady=4)
        tk.Label(row3, text="Expected:", font=SANS, bg=BG2, fg=TEXT2, width=9,
                 anchor="w").pack(side="left")
        self.e_expected = tk.Entry(row3, font=MONO, bg=BG3, fg=TEXT,
                                   insertbackground=TEXT, relief="flat",
                                   highlightthickness=1, highlightcolor=ACCENT)
        self.e_expected.pack(side="left", fill="x", expand=True, ipadx=0)
        tk.Label(row3, text="return value", font=("Segoe UI",9),
                 bg=BG2, fg=TEXT2).pack(side="left", padx=8)

        row4 = tk.Frame(form, bg=BG2)
        row4.pack(fill="x", padx=10, pady=4)
        tk.Label(row4, text="Mock:", font=SANS, bg=BG2, fg=TEXT2, width=9,
                 anchor="w").pack(side="left", anchor="n", pady=2)
        self.e_mock = tk.Text(row4, font=MONO, bg=BG3, fg=TEXT,
                              insertbackground=TEXT, relief="flat",
                              highlightthickness=1, highlightcolor=ACCENT,
                              height=3, width=40)
        self.e_mock.pack(side="left", fill="x", expand=True)
        tk.Label(row4, text="optional CMock\nsetup calls",
                 font=("Segoe UI",9), bg=BG2, fg=TEXT2, justify="left"
                 ).pack(side="left", padx=8)

        btn_row = tk.Frame(form, bg=BG2)
        btn_row.pack(fill="x", padx=10, pady=(4,10))
        tk.Button(btn_row, text="＋ Add Test Case", font=SANS_B,
                  bg=ACCENT, fg="white", relief="flat", padx=16, pady=5,
                  cursor="hand2", command=self.add_test_case
                  ).pack(side="left")
        tk.Button(btn_row, text="Clear form", font=SANS,
                  bg=BG3, fg=TEXT2, relief="flat", padx=10, pady=5,
                  cursor="hand2", command=self.clear_form
                  ).pack(side="left", padx=8)

        # Test cases table
        tbl_frame = tk.LabelFrame(right, text=" Test Cases ", font=SANS_B,
                                  bg=BG2, fg=TEXT2, bd=1, relief="flat",
                                  highlightbackground=BORDER, highlightthickness=1)
        tbl_frame.pack(fill="both", expand=True, pady=(0,6))

        cols = ("label","inputs","expected","mock")
        self.tree = ttk.Treeview(tbl_frame, columns=cols, show="headings",
                                 selectmode="browse", height=6)
        style = ttk.Style()
        style.theme_use("clam")
        style.configure("Treeview", background=BG3, foreground=TEXT,
                        fieldbackground=BG3, rowheight=26, font=MONO)
        style.configure("Treeview.Heading", background=BG2, foreground=TEXT2,
                        font=SANS_B, relief="flat")
        style.map("Treeview", background=[("selected", ACCENT)],
                  foreground=[("selected","white")])
        for c, w in [("label",140),("inputs",200),("expected",100),("mock",160)]:
            self.tree.heading(c, text=c.capitalize())
            self.tree.column(c, width=w, anchor="w")
        vsb = ttk.Scrollbar(tbl_frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=vsb.set)
        vsb.pack(side="right", fill="y")
        self.tree.pack(fill="both", expand=True, padx=4, pady=4)

        del_btn = tk.Button(tbl_frame, text="🗑 Delete Selected", font=SANS,
                            bg=BG3, fg=RED, relief="flat", padx=10, pady=3,
                            cursor="hand2", command=self.delete_selected_test)
        del_btn.pack(anchor="e", padx=8, pady=(0,6))

        # Run + output
        run_bar = tk.Frame(right, bg=BG)
        run_bar.pack(fill="x", pady=(0,4))
        self.run_btn = tk.Button(run_bar, text="▶  Run Tests", font=SANS_B,
                                 bg=GREEN, fg="#0a0a0a", relief="flat",
                                 padx=20, pady=7, cursor="hand2",
                                 command=self.run_tests)
        self.run_btn.pack(side="left")
        tk.Button(run_bar, text="📄  View Generated .c", font=SANS,
                  bg=BG3, fg=TEXT2, relief="flat", padx=10, pady=7,
                  cursor="hand2", command=self.view_generated
                  ).pack(side="left", padx=8)
        self.status_lbl = tk.Label(run_bar, text="", font=SANS_B, bg=BG, fg=TEXT2)
        self.status_lbl.pack(side="right", padx=10)

        self.output = scrolledtext.ScrolledText(right, font=MONO, bg="#0d0d1a",
                                                fg=TEXT, relief="flat",
                                                highlightthickness=1,
                                                highlightbackground=BORDER,
                                                height=12, state="disabled",
                                                insertbackground=TEXT)
        self.output.pack(fill="both", expand=False, pady=(0,0))
        self.output.tag_config("pass",   foreground=GREEN)
        self.output.tag_config("fail",   foreground=RED)
        self.output.tag_config("info",   foreground=YELLOW)
        self.output.tag_config("cmd",    foreground=TEXT2)
        self.output.tag_config("err",    foreground=RED)
        self.output.tag_config("normal", foreground=TEXT)

    # ── Helpers ──────────────────────────────────────────────────────────────
    def _clear_search(self):
        if self.fn_search.get() == "Search functions...":
            self.fn_search.delete(0, "end")
            self.fn_search.config(fg=TEXT)

    def _restore_search(self):
        if not self.fn_search.get():
            self.fn_search.insert(0, "Search functions...")
            self.fn_search.config(fg=TEXT2)

    def _filter_fns(self):
        q = self.fn_search.get().lower()
        if q == "search functions...": q = ""
        self.fn_listbox.delete(0, "end")
        for fn in self.store.functions:
            if q in fn["name"].lower():
                cnt = len(self.store.get_tests(fn["name"]))
                badge = f" [{cnt}]" if cnt else ""
                self.fn_listbox.insert("end", f"  {fn['name']}{badge}")

    def _fn_at(self, idx):
        text = self.fn_listbox.get(idx).strip().split("[")[0].strip()
        for fn in self.store.functions:
            if fn["name"] == text:
                return fn
        return None

    def open_folder(self):
        folder = filedialog.askdirectory(title="Select C Project Folder")
        if not folder: return
        self.store.set_project(folder)
        self.folder_lbl.config(text=folder[-55:] if len(folder)>55 else folder)
        self._filter_fns()
        self.log("INFO", f"Loaded project: {folder}\n")
        self.log("INFO", f"Found {len(self.store.functions)} functions.\n")

    def on_fn_select(self, _=None):
        sel = self.fn_listbox.curselection()
        if not sel: return
        fn = self._fn_at(sel[0])
        if not fn: return
        self.selected_fn = fn
        params = ", ".join(fn["params"]) if fn["params"] else "void"
        sig = f"{fn['ret']}  {fn['name']}({params})"
        self.fn_sig_lbl.config(text=sig)
        rel = os.path.relpath(fn["file"], self.store.project_folder)
        self.fn_file_lbl.config(text=rel)
        self._load_tests_table()
        # Update input hint
        if fn["params"]:
            hint = "  e.g. " + ", ".join(
                re.sub(r'\b(int|float|double|long|char\s*\*?|const\s+char\s*\*?|unsigned\s+\w+|uint\d+_t|int\d+_t)\b\s*\*?', '', p).strip() or "val"
                for p in fn["params"])
            self.inputs_hint.config(text=hint[:50])

    def _load_tests_table(self):
        self.tree.delete(*self.tree.get_children())
        if not self.selected_fn: return
        for tc in self.store.get_tests(self.selected_fn["name"]):
            inps = ", ".join(str(x) for x in tc.get("inputs", []))
            mock = (tc.get("mock","") or "")[:40]
            self.tree.insert("", "end", values=(
                tc.get("label",""), inps, tc.get("expected",""), mock))

    def add_test_case(self):
        if not self.selected_fn:
            messagebox.showwarning("No function", "Please select a function first.")
            return
        raw_inputs = self.e_inputs.get().strip()
        inputs = [x.strip() for x in raw_inputs.split(",") if x.strip()] if raw_inputs else []
        expected = self.e_expected.get().strip()
        label = self.e_label.get().strip()
        mock = self.e_mock.get("1.0", "end").strip()
        if not expected:
            messagebox.showwarning("Missing", "Expected value is required.")
            return
        self.store.add_test(self.selected_fn["name"], inputs, expected, label, mock)
        self._load_tests_table()
        self._filter_fns()
        self.clear_form()

    def clear_form(self):
        self.e_label.delete(0, "end")
        self.e_inputs.delete(0, "end")
        self.e_expected.delete(0, "end")
        self.e_mock.delete("1.0", "end")

    def delete_selected_test(self):
        sel = self.tree.selection()
        if not sel or not self.selected_fn: return
        idx = self.tree.index(sel[0])
        self.store.remove_test(self.selected_fn["name"], idx)
        self._load_tests_table()
        self._filter_fns()

    def view_generated(self):
        if not self.selected_fn:
            messagebox.showinfo("No function", "Select a function first.")
            return
        fn = self.selected_fn
        tcs = self.store.get_tests(fn["name"])
        header = Path(fn["file"]).with_suffix(".h")
        inc = header.name if header.exists() else Path(fn["file"]).name
        code = generate_test_c(fn, tcs, inc)
        win = tk.Toplevel(self)
        win.title(f"test_{fn['name']}.c")
        win.geometry("700x500")
        win.configure(bg=BG)
        txt = scrolledtext.ScrolledText(win, font=MONO, bg="#0d0d1a", fg=TEXT,
                                        relief="flat")
        txt.pack(fill="both", expand=True, padx=10, pady=10)
        txt.insert("end", code)
        txt.config(state="disabled")

    def run_tests(self):
        if not self.selected_fn:
            messagebox.showwarning("No function", "Select a function first.")
            return
        tcs = self.store.get_tests(self.selected_fn["name"])
        if not tcs:
            messagebox.showwarning("No tests", "Add at least one test case.")
            return
        self.run_btn.config(state="disabled", text="Running...")
        self.output.config(state="normal")
        self.output.delete("1.0", "end")
        self.output.config(state="disabled")
        self.status_lbl.config(text="Running...", fg=YELLOW)
        fn = self.selected_fn
        t = threading.Thread(target=self._run_thread, args=(fn, tcs), daemon=True)
        t.start()

    def _run_thread(self, fn, tcs):
        try:
            for kind, text in run_with_unity_directly(self.store.project_folder, fn, tcs):
                self.after(0, self._append_output, kind, text)
        finally:
            self.after(0, self._run_done)

    def _append_output(self, kind, text):
        self.output.config(state="normal")
        tag = {
            "RESULT": self._result_tag(text),
            "ERROR":  "err",
            "ERR":    "err",
            "CMD":    "cmd",
            "INFO":   "info",
            "OUT":    "normal",
        }.get(kind, "normal")
        if kind == "RESULT":
            self._colorize_result(text)
        else:
            self.output.insert("end", text, tag)
        self.output.see("end")
        self.output.config(state="disabled")
        # Update status
        if kind == "RESULT":
            if "FAIL" in text:
                self.status_lbl.config(text="✗ Some tests FAILED", fg=RED)
            elif "OK" in text or "PASS" in text:
                self.status_lbl.config(text="✓ All tests PASSED", fg=GREEN)

    def _result_tag(self, text):
        return "pass" if ("PASS" in text and "FAIL" not in text) else "fail"

    def _colorize_result(self, text):
        for line in text.splitlines(keepends=True):
            if ":PASS" in line or "OK" == line.strip():
                self.output.insert("end", line, "pass")
            elif ":FAIL" in line or "FAIL" in line:
                self.output.insert("end", line, "fail")
            elif line.startswith("-") or "Tests" in line:
                self.output.insert("end", line, "info")
            else:
                self.output.insert("end", line, "normal")

    def _run_done(self):
        self.run_btn.config(state="normal", text="▶  Run Tests")

    def log(self, kind, text):
        self.output.config(state="normal")
        tag = {"INFO":"info","ERROR":"err","CMD":"cmd"}.get(kind, "normal")
        self.output.insert("end", text, tag)
        self.output.see("end")
        self.output.config(state="disabled")


if __name__ == "__main__":
    app = App()
    app.mainloop()
